# route:
#     receiver: 'slack'

# receivers:
#     - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             text: "{{ .CommonAnnotations.description }}"
#             username: 'Prometheus'
#             channel: 'nvisible_de'
#             api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: [Alertname]
  # Send all notifications to me.
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: "sohaib.omar@emumba.com"
    from: "sohaib.omar@emumba.com"
    smarthost: smtp.gmail.com:587
    auth_username: "sohaib.omar@emumba.com"
    auth_identity: "sohaib.omar@emumba.com"
    auth_password: "nokiaemumba5320"
    send_resolved: true